declare GLOBAL_CONFIG_FILE="${HOME}/.config/zsh/global/global.zsh"
declare LOCAL_CONFIG_FILE="${HOME}/.config/zsh/local/local.zsh"

# Load global config Zsh config
source "${GLOBAL_CONFIG_FILE}"
# Load global config
[ -r "${LOCAL_CONFIG_FILE}" ] && source "${LOCAL_CONFIG_FILE}"

# Profile the setup
if type "zprof" > /dev/null 2>&1; then
  zprof | less
fi
